name: Build & Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag real-estate-ai:latest

      - name: Setup Railway CLI
        uses: MadeByThePinsHub/setup-railway-cli-action@v0.1.0

      - name: Deploy to Railway
        env:
          RAILWAY_CLI_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
        run: |
          railway link  # link project (only if not linked before)
          railway up --detach
